forum: Add ReadState. Fixes #81
prologin/concours-site pull request #111
Opened 2018-04-03 14:06 UTC by cafehaine

TODO:
- mark thread as read only if viewing the last page

2018-04-03 19:49 UTC, seirl commented on prologin/forum/views.py
> +        if not self.request.user.is_anonymous:
if self.request.user.is_authenticated

2018-04-03 20:22 UTC, seirl requested changes

2018-04-03 20:22 UTC, seirl commented on prologin/forum/models.py
> +    post = models.ForeignKey(Post, related_name='user_last_viewed',
Move this at the end of the class to be clear on the fact that the manytomany is between threads and users.

2018-04-03 20:22 UTC, seirl commented on prologin/forum/models.py
> +class LastViewed(models.Model):
Rename the class in ReadState, it conveys the intention better.

2018-04-03 20:22 UTC, seirl commented on prologin/forum/models.py
> +    thread = models.ForeignKey(Thread, related_name='user_last_viewed',
related_name='read_states'

2018-04-03 20:22 UTC, seirl commented on prologin/forum/models.py
> +    post = models.ForeignKey(Post, related_name='user_last_viewed',
related_name='read_states'

2018-04-03 20:22 UTC, seirl commented on prologin/forum/models.py
> +                             related_name='forum_last_viewed_post',
related_name='read_states'

2018-04-03 20:22 UTC, seirl commented on prologin/forum/views.py
> +                lastviewed.post = thread.last_post
Move those two lines after the except: block to factor them out.

2018-04-03 20:22 UTC, seirl commented on prologin/forum/views.py
> +                lastviewed = forum.models.LastViewed()
LastViewed(user=self.request.user, thread=thread)

2018-04-03 20:22 UTC, seirl commented on prologin/forum/views.py
> +        if self.request.user.is_authenticated:
We don't want to have that here, but rather do it in the model manager. Something like (untested):

```
def seen_by(self, user=None):
    return (self.get_queryset()
            .select_related('read_states')
            .filter(read_states__user=user)
            .annotate(seen=Case(
                When(post=F('read_states__post'), then=Value(1)),
                default=Value(0)
                output_field=BooleanField()
            )))

```

2018-04-03 20:22 UTC, seirl commented on prologin/forum/templates/forum/stub_forum_thread.html
> +      <h3>{{ thread.title }}{% if not thread in read_threads %}*{% endif %}</h3>
Use \<strong> for unread threads

2018-04-03 22:43 UTC, seirl commented
We should only mark the thread as read if the user looks at the last page of the thread, not any page.

2018-04-04 07:34 UTC, zopieux requested changes

2018-04-04 07:34 UTC, zopieux commented on prologin/forum/views.py
> +            except forum.models.LastViewed.DoesNotExist:
Seems like the exact use case of [`update_or_create`](https://docs.djangoproject.com/en/2.0/ref/models/querysets/#update-or-create).

2018-04-04 08:08 UTC, cafehaine commented on prologin/forum/views.py
> +            except forum.models.LastViewed.DoesNotExist:
didn't know this existed, thanks !

2018-04-04 11:45 UTC, seirl commented on prologin/forum/models.py
> +
You also need a unique_together between user and thread.

2018-04-04 19:41 UTC, seirl requested changes

2018-04-04 19:41 UTC, seirl commented on prologin/forum/templates/forum/stub_forum_thread.html
> +        {% if thread.seen %}<h3>{{ thread.title }}</h3>
Maybe just <h3 {% if thread.seen %}class="thread-unread"{% endif %}> with the corresponding font-weight: bold; entry

2018-04-04 19:41 UTC, seirl commented on prologin/forum/views.py
> +
remove

2018-04-04 22:08 UTC, merged