documents: add mail to contestant & lycee
prologin/concours-site pull request #122
Opened 2018-04-10 17:58 UTC by pguenezan

2018-04-12 11:21 UTC, seirl requested changes

2018-04-12 11:21 UTC, seirl commented on prologin/contest/models.py
> +        return cls.objects.select_related('center').get(edition__year=year, type=cls.Type.qualification.value)
- I know the file isn't PEP-8 compliant, but could we avoid adding more non compliant stuff?
- Why do you need to select_related('center')?

2018-04-12 11:21 UTC, seirl commented on prologin/documents/templates/documents/courrier-lancement-candidat.tex
> +\documentclass[11pt]{article}
Why isn't this using prologin-letter.sty?

2018-04-12 11:21 UTC, seirl commented on prologin/documents/templates/documents/courrier-lancement-lycee.tex
> +\documentclass[9pt]{article}
Why isn't this using prologin-letter.sty?

2018-04-12 11:21 UTC, seirl commented on prologin/documents/views.py
> +        context['pres'] = team.models.TeamMember.objects.get(year=self.year, role_code=team.models.Role.president.name)
79cols

2022-07-31 14:59 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/122

2022-07-31 14:59 UTC, closed without merging