Add a note for macOS setup
prologin/concours-site pull request #123
Opened 2018-04-16 09:52 UTC by alexkirsz

2018-04-17 21:08 UTC, zopieux commented
That day has come.

2018-04-18 13:03 UTC, seirl requested changes

2018-04-18 13:03 UTC, seirl commented on README.md
> +On macOS, if you get an `ImportError: MagickWand shared library not found.`, you can refer to this [StackOverflow answer](https://stackoverflow.com/questions/37011291/python-wand-image-is-not-recogni
Can you wrap that to 79 cols?

2018-08-26 11:40 UTC, closed without merging

2018-08-26 14:15 UTC, multun commented
merged as 500964c