Dashboard
prologin/concours-site pull request #129
Opened 2018-05-11 09:47 UTC by cafehaine

Updates #67 

Features from issue that aren't implemented:
 - wrong permissions on problems/ (eg. readable before event starts)
 - wrong permissions on archives/ (eg. readable before event stops)

2018-10-11 19:53 UTC, zopieux requested changes
This is a good start, but to be useful this needs much more human explanations of what is happening. There should be more text than code in this feature! Add explanations of what a test is checking, and how to fix it. You don't have to i18n, that's too much hassle. You could write the explanations in class/def docstrings and use `my_checker.__doc__` to render/display them in your view.

2018-10-11 19:53 UTC, zopieux commented on prologin/dashboard/views.py
> +statusFetchers = defaultdict(lambda: [])
`defaultdict(list)`

2018-10-11 19:53 UTC, zopieux commented on prologin/dashboard/views.py
> +        context.update({'sections': statusFetchers})
`snake_case`

2018-10-11 19:53 UTC, zopieux commented on prologin/dashboard/views.py
> +class status(object):
PEP-8, also why do you inherit from `object`?
I would replace this decorator with a simple class attribute, that's what Django/we do everywhere else, eg. class view attributes (`template_name = `). Just add `category =`.

2018-10-11 19:53 UTC, zopieux commented on prologin/dashboard/views.py
> +def fetchExpiredUserActivations():
PEP-8

2018-10-12 15:39 UTC, cafehaine commented
@Zopieux your comments should be fixed

2018-10-15 18:37 UTC, zopieux submitted a review, later dismissed
That's much better!

2018-10-15 18:37 UTC, zopieux commented on prologin/dashboard/views.py
> +        for line in self.__doc__.strip().splitlines():
[`textwrap.dedent`](https://docs.python.org/3/library/textwrap.html#textwrap.dedent)

2018-10-15 18:37 UTC, zopieux commented on prologin/dashboard/views.py
> +        return '<br>'.join(output)
What about Markdown instead? So that code can be code! Rendering code as normal text is THE. WORSE.

2018-10-15 18:37 UTC, zopieux commented on prologin/dashboard/views.py
> +    UserActivation.objects.filter(expiration_date__lt=timezone.now()).delete()
Wrap into Markdown code.

2018-10-15 18:37 UTC, zopieux commented on prologin/dashboard/views.py
> +    You shouldn't remove these unless you want to piss of the users.
piss off

2018-10-15 18:37 UTC, zopieux commented on prologin/dashboard/views.py
> +class AwaitingUserActivations(Status):
What is the purpose of this anyway? This looks like a good candidate for Grafana (I think it's already there), not for an issue-solving dashboard.

2018-10-15 18:37 UTC, zopieux commented on prologin/dashboard/views.py
> +    Contestant.objects.filter(
Code.

2022-07-31 14:58 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/129

2022-07-31 14:58 UTC, closed without merging