Integration gcc
prologin/concours-site pull request #139
Opened 2018-09-09 11:49 UTC by cafehaine

TODO TODO TODO !
================

Before merging with master
-----------------------------------

 - [x] ~Add a "Complete your profile"  form before subscription~ -> Add a disclaimer asking to update the profile before submitting application
 - [x] Recheck that all permissions are correctly considered
 - [x] Apply last coding style issues raised by zopieux
 - [x] Make login and register page clearer on the fact that it is a Prologin account 

Views missing templates/context
-------------------------------

- [x] Index view
- [x] Editions index view
- [x] Edition view
- [x] Newsletter views
- [x] Stage signup views
- [x] Candidates review views
- [x] Login & Register views
- [x] User profile view
- [x] Button to switch language
- [x] Handle messages

CSS
---

### Style issues

- [x] Make the information more compact (many people complained that you need to scroll a lot on desktops to catch informations)

### Template issues

The style is based on a template used from [html5up](https://html5up.net/), but we should not stick to this and make it as maintainable as it can be

 - [x] Stop using bootstrap-like grid features defined in grid.css (using vanilla css grids for example)
 - [ ] Switch to bootstrap

Behaviour
---------

### Application

 - [x] Candidate's form
 - [x] Check validity of inscription, attach to user session
 - [ ] Ask candidates to confirm their participation once they are accepted
    * send a mail to anounce selection for an event, with a confirmation link
    * add a button on the application summary itself
 - [ ] Implement file field type
    * define maximal size and allowed file types in meta field ?
    * store files in a dedicated model, and link to their identifier in the generic "answer" model ?

### Review

 - [x] Trainers permissions on accepting candidates for specific events
 - [x] Apply some tags to reviews
 - [ ] Filter tool on pending applications
 - [ ] Compute a counter of previous applications

Content
-------

 - [x] Translate the app in English and use french as a translation
 - [ ] Rework the content: Yona highlighted that part of the content was repetitive and not straighforward enough

Random issues
-------------

- [x] Rebase the branch which start on a random commit, too early in master
- [x] Clean commit history

Other
-----

- [x] New logo
- [ ] Integrate docs
- [ ] Allow downloading old TPs
- [ ] Check mail plugin integration/create a few basic requests

2018-11-17 16:57 UTC, zopieux reviewed
Global test comment. Please ignore.

2019-02-06 23:35 UTC, zopieux requested changes
Première passe rapide. J'ai lu 5% du code tout au plus.

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/admin.py
> +from gcc.models import Question, Form, Answer
Ne split pas les imports aléatoirement comme ça.
```
import (foo,
        bar)
```

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +from datetime import date
Trop de lignes blanches.

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +    email = forms.EmailField(label='Adresse électronique', max_length=254)
i18n

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +    Initialize a django form with fields described in models.Question
`"""{Build,Create} a form to answer qualification quiz questions."""`

Ne t'emmerde pas avec des précisions évidentes dans le contexte ("django", "fields"), explique surtout l'utilité.

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +        `form` and `user` are the parameters of function
On le sait, c'est dans le code !

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +            self.form = form
Pourquoi les stocker dans la classe si c'est déjà dans le scope de la fonction ?

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +                    'help_text': question.comment
Virgule.

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +                fieldId = 'field' + str(question.pk)
string formating

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +                fieldId = 'field' + str(question.pk)
snake case, string formating

Aussi tu réutilises plusieurs fois le même code, c'est une bug-bombe à retardement. Fais-en une fonction de génération du field id.

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +            signup_start__lt = date.today(),
`__range=(begin, end)`

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +        self.fields['priority1'].choices = events_selection
Tu peux chaîner les `=` pour éviter de répéter `events_selection`.

2019-02-06 23:35 UTC, zopieux commented on prologin/gcc/forms.py
> +        Saves the new applications.
Singulier.

2019-02-12 13:40 UTC, seirl requested changes

2019-02-12 13:40 UTC, seirl commented on prologin/gcc/models.py
> +    RGPD-safe usage of reviews.
GDPR

2019-02-12 13:40 UTC, seirl commented on prologin/gcc/models.py
> +    # Whishes of the candidate
Wishes

2019-02-12 16:28 UTC, remi-dupre commented on prologin/gcc/forms.py
> +            signup_start__lt = date.today(),
I want the current date in a range defined by two fields, and not a field bounded by two values, I'm not sure how to do this differently

2019-02-14 21:23 UTC, zopieux requested changes
* Il y a une bonne moitié des strings qui sont pas i18n, que ce soit dans le Python ou les templates.
* Il faut vraiment ajouter une vérif sur la newsletter, là c'est un trou de sécurité.
* L'inscription & login dupliqués de Prologin est moche, mais c'est chiant à faire bien, donc on unifiera plus tard. L'idée étant certainement d'avoir une page de login partagée, moins brandée Prologin, où on peut changer le logo (ou en tout cas ajouter celui de GCC à côté de Prologin) pour ne pas confuse les visiteurs de l'un ou l'autre site.
* J'ai pas review les templates, mais le rendu est OK. Pas pu essayer toutes les vues cela dit.

2019-02-14 21:23 UTC, zopieux commented on prologin/sponsor/models.py
>      objects = models.Manager()
J'ai récemment découvert cet idiom que je trouve cool car composable et simple :
```python
class SponsorQuerySet(models.QuerySet):
    def active(self):
        return self.filter(active=True)
    def for_prologin(self):
        return self.active().filter(for_prologin=True)
    def for_gcc(self):
        return self.active().filter(for_gcc=True)
# ...
class Sponsor(…):
    objects = SponsorQuerySet.as_manager()
# ...
Sponsor.objects.for_prologin().filter(…)
```

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/views.py
> +        return super().form_valid(form)
Le feedback peut être remplacé par un `messages.success`. Mais surtout je conseille le mail de confirmation, pour implémenter la désinscription. Cf. l'autre commentaire.

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/views.py
> +class NewsletterUnsubscribeView(FormView):
Utiliser `django.views.generic.edit.DeleteView`, qui supprime presque toute la logique de `form_valid`.

Par contre il faut absolument ajouter une forme de vérification, sinon n'importe qui peut désinscrire n'importe quel mail qui lui appartient pas. Design classique:
1. à l'inscription, envoyer un mail de confirmation qui contient un lien désinscription (ça fait aussi office de feedback, cf. autre commentaire)
2. utiliser une [signature](https://docs.djangoproject.com/fr/2.1/topics/signing/) qui est dans ce lien
3. la signature est vérifiée dans cette vue avant suppression

La fonction qui génère la signature peut aller dans le modèle `SubscriberEmail`.

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/staff_views.py
> +        return len(Corrector.objects.filter(event__id=self.kwargs['event'],
`.exists()`

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/staff_views.py
> +class CanEditLabelsPermissionMixin(PermissionRequiredMixin):
Essayez d'utiliser le framework de rules plutôt, comme ailleurs sur le site.

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/models.py
> +        return len(current_events) > 0
`.exists()`

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/models.py
> +        return bool(Applicant.objects.filter(user=user, edition=self))
`.exists()`

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/models.py
> +        ordering = ['year']
`-year` (on préfère les éditions récentes non ?)

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/forms.py
> +        event_wishes = EventWish.objects.filter(applicant=applicant)
Coûteux. Déplacer en-dessous des vérifs qui raise.

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/models.py
> +    pending = 0  # the candidate hasn't finished her registration yet
Comment distinguer les candidatures en cours d'écriture des candidatures finies mais pas encore reviewed par le staff?

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/models.py
> +        try:
```python
applicant, created = Applicant.objects.get_or_create(
    user=user, edition=edition, default={status: ApplicantStatusTypes.pending.value})
return applicant
```

2019-02-14 21:23 UTC, zopieux commented on prologin/gcc/templates/gcc/application/review.html
> +                    This could also be implemented like some kind of comment section?
Wat

2019-02-14 21:37 UTC, multun commented on prologin/gcc/forms.py
> +        event_wishes = EventWish.objects.filter(applicant=applicant)
les queryset sont lazy, ça change rien (même si c'est quand même logique de les mettre en dessous)

2019-02-14 21:41 UTC, zopieux commented on prologin/gcc/forms.py
> +        event_wishes = EventWish.objects.filter(applicant=applicant)
Oui, ma justification est débile, mais ça reste valide pour la lisibilité.

2019-02-15 07:59 UTC, remi-dupre commented on prologin/gcc/models.py
> +    pending = 0  # the candidate hasn't finished her registration yet
Je crois que j'avais considéré qu'une fois que l'ordre des vœux est donné la candidature est valide. Mais effectivement maintenant que tu le dis ce serait bien que les candidates aient un bouton pour valider et rendre non éditable les formulaires.

2019-02-15 08:03 UTC, remi-dupre commented on prologin/gcc/models.py
> +        try:
:mind_blowed: much things to reimplement :o

2019-02-15 08:04 UTC, remi-dupre commented on prologin/gcc/templates/gcc/application/review.html
> +                    This could also be implemented like some kind of comment section?
Just deprecated stuff ... Sorry:3

2019-02-15 09:12 UTC, remi-dupre commented on prologin/gcc/models.py
> +        ordering = ['year']
Mais ça deviendrait peu intuitif nan ? Par exemple Edition.objects.last() ça deviendrait l’édition la plus vieille ?

2019-02-17 12:30 UTC, zopieux requested changes

2019-02-17 12:30 UTC, zopieux commented on prologin/gcc/models.py
> +    def for_user_and_edition(user, edition):
pas de self et la méthode n'est pas static

2019-02-17 12:30 UTC, zopieux commented on prologin/gcc/models.py
> +        ordering = ['year']
non Django est pas bête et utilise latest_by pour last et first. Précise le dans Meta si t'as pas confiance dans le comportement par défaut.

2019-02-17 12:30 UTC, zopieux commented on prologin/gcc/staff_views.py
> +        assert(event.edition.year == kwargs['edition'])
Pas de assert dans une vue web. Sois tu as confiance que c'est bon soit tu handle.

2019-02-17 12:30 UTC, zopieux commented on prologin/gcc/templates/gcc/application/validation.html
> +            {% trans "From {{event.event_start}} to {{event.event_end}}" %}<br />
Euhhh Django supporte les variables dans les trans maintenant ? ce serait bien, mais je crois pas. D'où blocktrans. Oui le moteur de templates Django est une daube infâme.

2019-02-17 12:30 UTC, zopieux commented on prologin/gcc/views.py
> +        self.author = Author(pk=self.kwargs[self.pk_url_kwarg])
wait que vient faire Zinnia là dedans ?

2019-02-18 18:30 UTC, fnareoh commented on prologin/gcc/views.py
> +        self.author = Author(pk=self.kwargs[self.pk_url_kwarg])
j'ai repris ça de [là](https://github.com/prologin/site/blob/6e325b2337b3a736ab940035659d72cec8442992/prologin/users/views.py#L127) :o

2019-02-18 21:00 UTC, fnareoh commented on prologin/gcc/views.py
> +        self.author = Author(pk=self.kwargs[self.pk_url_kwarg])
Autant pour moi, j'avais changé d'avis entre temps sur ce que je voulais faire de cette page.

2019-03-03 18:27 UTC, merged