Fix some initial setup requirements
prologin/concours-site pull request #145
Opened 2018-09-18 17:39 UTC by remi-dupre

2018-10-07 19:13 UTC, seirl commented on README.md
> + * It is required to setup a local Postgres database and use that instead.
Why "instead"?

Shouldn't this be earlier in the README?

2018-10-07 21:57 UTC, seirl commented on README.md
> +             'HOST': 'localhost',
Can we remove HOST, USER and PASSWORD? People should use peer auth instead, it's easier to configure.

2018-10-11 19:45 UTC, zopieux approved these changes

2018-10-11 19:45 UTC, zopieux commented on README.md
> +             'ENGINE': 'django.db.backends.postgresql_psycopg2',
Just `postgresql`

2018-10-11 19:45 UTC, zopieux commented on README.md
> +Modify database's connection accordingly:
No `'s`

2018-10-13 13:48 UTC, seirl requested changes

2018-10-13 13:48 UTC, seirl commented on prologin/prologin/settings/conf.sample.py
> +        'HOST': 'localhost',
Why?

2018-10-13 13:54 UTC, remi-dupre commented on prologin/prologin/settings/conf.sample.py
> +        'HOST': 'localhost',
It wasn't consistant with the readme, I preferred verbosity

2018-10-13 23:11 UTC, merged