problems: warn for integer named testcases
prologin/concours-site pull request #148
Opened 2018-10-08 16:15 UTC by remi-dupre

Using an integer as a name for a testcase can lead to unexpected behaviors while parsing problem.prop.
Thus, is should be unrecommended as long as the parser tries to cast values to integers.

2018-10-10 19:37 UTC, zopieux requested changes
I'm not convinced that problem validation should go in a random Django web view. This is `problems/`'s concern. It could be okay to put that in #67, which has the explicit goal of finding random stupid/inconsistencies across our data models. But then again, this should end up in `problems/`.

2018-10-10 19:37 UTC, zopieux commented on prologin/problems/views.py
> +        #   case section, a warning is displayed to staff members if there is
Please don't indent comments.

2018-10-10 19:37 UTC, zopieux commented on prologin/problems/views.py
> +                    ' while parsing <em>problem.props</em>, so you should'
`<code>`

2019-01-19 16:16 UTC, remi-dupre commented
Not really usefull

2019-01-19 16:16 UTC, closed without merging