contest: add optional question  "How did you learn about the contest"
prologin/concours-site pull request #155
Opened 2018-10-22 22:02 UTC by fnareoh

Adresses #42

2018-10-22 22:03 UTC, fnareoh commented
Currently lacking translations

2018-10-22 22:17 UTC, seirl requested changes

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +    already_knows = (0, _("I already knew it"))
"I don't remember", maybe? You have to have known it by something at some point.

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +    web_site = (1, _("By the website"))
You can't learn about it from the website, you have to know how to go to our website first

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +    social_medias = (2, _("By social medias"))
From social media

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +    poster = (3, _("By the poster"))
"From the poster in my school/university"?

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +    svj = (5, _("Magazine science et vie junior"))
If we go into such specific details, we'll need to update that list depending on the editions. If that's the case, then this needs to be a database table, not something in the code.

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +    word_of_mouth = (4, _("By word of mouth"))
"From a friend" maybe?

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +class Learn_about_contest(ChoiceEnum):
Use CamelCase for classes

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +    other = (6, _("Other way"))
"Some other way"

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +    other = (6, _("Other way"))
Maybe add "Another programming contest"?

2018-10-22 22:17 UTC, seirl commented on prologin/contest/models.py
> +        verbose_name=_("How did you know the contest"),
s/know/learn about"

Question mark at the end.

2018-10-23 23:42 UTC, seirl requested changes

2018-10-23 23:42 UTC, seirl commented on prologin/contest/models.py
> +    svj = (5, _("From a journal"))
The field is still called "SVJ". Also "From a journal" isn't very clear, so you should probably expand on that.

2018-10-23 23:42 UTC, seirl commented on prologin/contest/models.py
> +    doesnt_know = (0, _("I don't remember"))
I don't know according to what the fields are sorted, but that would be better at the end of the dropdown.

2018-10-23 23:42 UTC, seirl commented on prologin/contest/models.py
> +    social_medias = (2, _("From social media"))
no s at social_media

2018-10-23 23:43 UTC, seirl requested changes

2018-10-23 23:43 UTC, seirl commented on prologin/contest/models.py
> +    word_of_mouth = (4, _("From a friend"))
Update the field name to "friend" maybe?

2018-10-28 14:34 UTC, seirl approved these changes

2018-10-28 14:35 UTC, merged