Add a docker-compose automated setup
prologin/concours-site pull request #157
Opened 2018-10-29 22:28 UTC by multun

2018-10-29 22:31 UTC, multun commented
Docs missing, coming soon

2018-11-18 23:50 UTC, zopieux requested changes
Please move Docker-specific stuff into a folder, eg. `dev/`. Put any `Dockerfile` or Docker-only shell script (eg. `docker_init.sh`) in it.

2018-11-18 23:51 UTC, zopieux commented on docker-compose.yml
> +    image: postgres
For the love of God, `postgres:alpine`.

2018-11-19 00:19 UTC, seirl commented
Will this replace/be merged with the Dockerfile at the root? Since it's only used for asset generation right now, both the dockerfile and the script should go in assets/ unless you plan to merge everything.

2018-11-19 00:19 UTC, seirl commented
@Zopieux `docker` please, it's a lot more explicit than `dev`.

2018-11-29 22:10 UTC, seirl requested changes

2018-11-29 22:10 UTC, seirl commented on prologin/prologin/settings/docker_dev.py
> +        'HOST': 'prologin_site_db',
Why not peer auth?

2018-11-29 22:10 UTC, seirl commented on prologin/prologin/settings/docker_dev.py
> +PROLOGIN_EDITION = (datetime.now().year + 1)
I think this will only work for 4 months.

I think the real solution would be to move away from having that stuff in the settings and store it in the db instead, but I don't know what the cost of that would be performance-wise. Anyway, worth filing an issue.

2018-11-29 22:10 UTC, seirl commented on prologin/prologin/settings/docker_dev.py
> +from .common import *
I don't think this settings file is significantly different from conf.sample.py?

2020-09-22 16:55 UTC, AurelReb commented
The docker setup is now fully working. Thanks @multun  for your work

2020-09-22 16:58 UTC, seirl commented
I think you're missing the celery worker in the docker-compose. Can you add that?

2020-09-27 16:40 UTC, AurelReb commented
> I think you're missing the celery worker in the docker-compose. Can you add that?

Done :)

2020-12-08 19:07 UTC, Nhqml commented
@AurelReb I'm wondering why you've put multiple '&&' in [docker_init.sh](https://github.com/prologin/site/blob/fd1fa0fb5a07189fa0d984408ace4a6a832b6f31/docker/docker_init.sh), is it to stop the script in case any command fails?

2020-12-08 19:18 UTC, AurelReb commented
Exactly

2020-12-08 19:19 UTC, Nhqml commented
Ok, then I suggest using `set -e` , it will be more explicit and less bloated imo.

2020-12-08 19:23 UTC, AurelReb commented
@Nhqml I didn't understand what you've changed about the celery worker in docker-compose

2020-12-08 19:26 UTC, Nhqml commented
`-l` is not a valid option for `celery`, I fixed that. (it is a `worker` subcommand option)

2020-12-08 19:54 UTC, AurelReb commented
Oh ok thanks

2020-12-11 11:18 UTC, Nhqml commented on docker/docker-compose.yml
> +    restart: always
is there any reason to use `restart: always` instead of `on-failure` or `unless-stopped`?

2021-02-18 11:55 UTC, Elfikurr commented
It would be nice to add a README or update the existing README.

2022-07-31 14:58 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/157

2022-07-31 14:58 UTC, closed without merging