mailing: foolproof message singular if one recipient
prologin/concours-site pull request #177
Opened 2019-01-02 23:26 UTC by Melyodas

Signed-off-by: Matthieu Moatti <moatti_m@epita.fr>

2019-01-03 07:32 UTC, seirl commented
I don't think i18n works for "person"/"people"

2019-01-03 09:41 UTC, Melyodas commented
> I don't think i18n works for "person"/"people"

What do you mean ?

2019-01-04 14:41 UTC, seirl requested changes

2019-01-04 14:41 UTC, seirl commented on prologin/mailing/forms.py
> +        phrase = cls.FOOLPROOF_PHRASE % {'n': count, 'p' : 'people' if n > 1 else 'person'}
No i18n.

2019-01-04 14:41 UTC, closed without merging

2019-01-04 14:41 UTC, Melyodas commented
This is useless.