Refactor contestant submissions
prologin/concours-site pull request #187
Opened 2019-01-10 15:50 UTC by cafehaine

This will close part of #109 

TODO List:
- [x] Add Contestant.semifinal_submissions
- [x] Add Contestant.qualification_submissions
- [x] Remove completely the date range handling in contest/staff_views.py
- [ ] Also use this function where it's misused in contest/models.py, for instance semifinal_lines_of_code or semifinal_problems_score.

2019-01-20 14:25 UTC, cafehaine commented
grepping semifinal_problems_score on the whole repo did not bring any result except the function definition.
Should we just remove it ?

2019-01-22 10:29 UTC, seirl commented
No, it's useful when writing email templates. "You have submitted X lines for ex5" etc.

2019-01-22 10:39 UTC, seirl requested changes

2019-01-22 10:39 UTC, seirl commented on prologin/contest/models.py
> +    @cached_property
Don't use `@cached_property` for stuff that returns querysets. There's already a caching mechanism inside and we don't want to interfere with that.

2019-01-22 10:39 UTC, seirl commented on prologin/contest/models.py
> +        return SubmissionCode.objects.select_related(
Suboptimal to do two queries here, but since this will be replaced by `event=event` after the migration to the new data model, I guess this can stay.

2019-01-22 10:39 UTC, seirl commented on prologin/contest/models.py
> +    @cached_property
Same, don't use cached_property

2019-01-22 10:39 UTC, seirl commented on prologin/contest/models.py
> +    #@cached_property
Uncomment that and fix if necessary

2019-01-22 10:39 UTC, seirl commented on prologin/contest/staff_views.py
> +            # prevent caching.
There shouldn't be a need for caching here, you should just be doing a single request every time that you can't avoid.

2022-07-31 14:58 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/187

2022-07-31 14:58 UTC, closed without merging