sponsor: add sponsor view
prologin/concours-site pull request #196
Opened 2019-01-29 14:58 UTC by pguenezan

- still need to rework the page style

2019-03-24 23:11 UTC, seirl requested changes

2019-03-24 23:11 UTC, seirl commented on prologin/prologin/templates/prologin/main-menu.html
> +  <li class="{% active '^/sponsors/' %}"><a href="{% url 'sponsors:index' %}">{% trans "Sponsors" %}</a></li>
I know this isn't final, but I really don't want to add too much clutter to that menu. I'd rather have a "See all the sponsors" button on the homepage.

2019-04-23 20:01 UTC, seirl requested changes

2019-04-23 20:01 UTC, seirl commented on prologin/documents/templates/documents/interviews.tex
> -        \item Hobbies non informatiques ?
What is this doing here? And why?

2019-04-23 20:01 UTC, seirl commented on prologin/homepage/templates/homepage/sponsors.html
> +  <a href="{% url 'sponsors:index' %}" class="btn btn-default btn-block">
Don't use a button for that, it's a link, it should look like a link.

2019-04-23 20:01 UTC, seirl commented on prologin/prologin/urls.py
> +    path('sponsors/', include('sponsor.urls', namespace='sponsors')),
Why would you create a whole new module for a single static page?

2019-04-23 20:01 UTC, seirl commented on prologin/sponsor/templates/sponsor/index.html
> +    <p>{% blocktrans %}Looking for Prologin's last year poster? 1996 final's statement? 2003 quiz?
wat

2019-04-23 20:01 UTC, seirl commented on prologin/sponsor/templates/sponsor/index.html
> +                <a href="{{ sponsor.site }}" style="width: 100%; display: block; text-align: center">
Don't hardcode style in the HTML template

2019-04-23 20:15 UTC, remi-dupre commented on prologin/homepage/templates/homepage/sponsors.html
> +  <a href="{% url 'sponsors:index' %}" class="btn btn-default btn-block">
I tried several design, the only feedback I got was for the opposite :/

2019-04-23 20:19 UTC, remi-dupre commented on prologin/prologin/urls.py
> +    path('sponsors/', include('sponsor.urls', namespace='sponsors')),
There was already a `sponsors` module holding related models, it seems it should be the right place to incorporate this page?

2019-04-23 20:21 UTC, seirl commented on prologin/prologin/urls.py
> +    path('sponsors/', include('sponsor.urls', namespace='sponsors')),
Ah, okay then 👍

2019-05-14 21:42 UTC, merged