add a GPL 3 licence
prologin/concours-site pull request #216
Opened 2019-06-24 19:02 UTC by remi-dupre

2020-01-20 15:35 UTC, seirl commented
I rebased this PR on master.

2020-01-20 15:36 UTC, seirl requested changes

2020-01-20 15:36 UTC, seirl commented on COPYING
> +                    GNU GENERAL PUBLIC LICENSE
This is already present in markdown format, please remove it

2020-01-20 15:36 UTC, seirl commented on prologin/contest/staff_views.py
> +# Copyright (C) <2015> Association Prologin <association@prologin.org>
Year shouldn't be inside `<>`

2022-07-31 14:58 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/216

2022-07-31 14:58 UTC, closed without merging