centers: add absolute url getter
prologin/concours-site pull request #226
Opened 2019-10-24 08:38 UTC by Idotno-1

Fixes #222

2019-10-24 11:08 UTC, alarsyo commented on prologin/centers/models.py
> +        return "https://www.openstreetmap.org/?mlat={0:.6f}&mlon={1:.6f}#map=16/{0:.6f}/{1:.6f}".format(self.lat, self.lng)
You could use [f strings](https://www.python.org/dev/peps/pep-0498/) here instead :)

2019-10-24 11:21 UTC, seirl requested changes
Thanks, but the idea was to have an absolute url to the centers page *in prologin.org*. It should redirect to something like `prologin.org/centers#center-XXX`, not OSM.

2019-10-27 21:29 UTC, seirl requested changes

2019-10-27 21:29 UTC, seirl commented on prologin/centers/templates/centers/map.html
> +        var m = center_markers[on_map_nb];
Can't you just call showCenter(on_map_mb) here?

2019-10-27 21:29 UTC, seirl commented on prologin/centers/models.py
> +        return f'https://www.openstreetmap.org/?mlat={self.lat:.6f}&mlon={self.lng:.6f}#map=16/{self.lat:.6f}/{self.lng:.6f}'
I don't think this fits in 79 columns.

2019-10-27 21:29 UTC, seirl commented on prologin/centers/models.py
> +    def get_full_map_url(self):
`get_osm_url()` maybe?

2019-10-27 21:29 UTC, seirl commented on prologin/centers/templates/centers/map.html
> +          createMarker({{ center.lat }}, {{ center.lng }}, "{{ center.name|escapejs }}", body, {{ center.id }});
Doesn't fit 79 columns

2019-10-28 11:51 UTC, Idotno-1 commented on prologin/centers/templates/centers/map.html
> +        var m = center_markers[on_map_nb];
Indeed. However, I was faced with the following problem: The Popup of the center opens but I can't get the map to focus on the selected center. May it be because 'panTo' is interrupted during the animation? In which case, how can I tell 'panTo' not to animate the panning when the center is given in the fragment?

2019-10-28 12:08 UTC, zopieux commented
Unsolicited opinion: I don't care about the 79 columns for HTML (and JS embedded inside HTML). HTML is a terrible, whitespace sensitive language, so I've abandoned that fight 10 years ago.

2019-10-28 22:16 UTC, Idotno-1 commented on prologin/centers/templates/centers/map.html
> +        var m = center_markers[on_map_nb];
After further investigation, I found out how to deactivate the animation using `map.panTo(m.getLatLng(), { animate: false})`. However this did not solve the focus issue.

Neither `map` nor `m` are null, and `m.getLatLng()` returns a correct results. 

Being still new at this, I'm not against a little help  ^^

2019-11-25 19:04 UTC, seirl requested changes

2019-11-25 19:04 UTC, seirl commented on prologin/centers/models.py
> +        return f'https://www.https://prologin.org/center/#center-{self.id}'
The domain shouldn't be hardcoded (just use a relative path) and there's an error in it anyway :-)

2019-11-29 22:36 UTC, zopieux commented on prologin/centers/models.py
> +        return f'https://www.https://prologin.org/center/#center-{self.id}'
And by "relative" seirl actually means absolute, but without the host, something you get with `reverse()`. Never hardcode a URL. You just have to append the hash (the part after #) to what `reverse('centers:map')` returns.

2019-11-30 10:02 UTC, Idotno-1 commented on prologin/centers/models.py
> +        return f'https://www.https://prologin.org/center/#center-{self.id}'
As stated in #222, 

> Centers should have a `get_absolute_url()` that redirects to a map of the center. This would allow us to give this URL in email templates

To achieve this goal, I'd say it is necessary to provide the host aswell in the URL. I was not able to figure out a way to get the host without the 'request'. That led to hardcoding the URL.

Which indeed allowed an error to slip into the URL. :p

2019-11-30 10:30 UTC, zopieux commented on prologin/centers/models.py
> +        return f'https://www.https://prologin.org/center/#center-{self.id}'
Then I think we have a setting with the host, just use that.

2019-11-30 15:09 UTC, Idotno-1 commented on prologin/centers/models.py
> +        return f'https://www.https://prologin.org/center/#center-{self.id}'
Okay, thank you for the advice!

2019-12-25 18:24 UTC, seirl requested changes

2019-12-25 18:24 UTC, seirl commented on prologin/centers/views.py
> +class CenterSpecificView(RedirectView):
Rename this CenterDetailView, it's the usual name for that

2019-12-25 18:24 UTC, seirl commented on prologin/centers/views.py
> +        return f'{settings.SITE_BASE_URL}{reverse("centers:map")}#center-{self.kwargs["id"]}'
Remove the host here

2019-12-25 19:16 UTC, seirl approved these changes

2019-12-25 19:19 UTC, seirl requested changes

2019-12-25 19:19 UTC, seirl commented on prologin/centers/models.py
> +        return f'{reverse("centers:map")}{self.id}'
use the `kwargs` argument of reverse()

2019-12-25 20:22 UTC, seirl approved these changes

2020-01-19 13:47 UTC, merged