sponsor: rework sponsors page
prologin/concours-site pull request #233
Opened 2019-12-17 11:23 UTC by Idotno-1

- Adding ranks to the sponsors (gold / silver / bronze )
- Displaying sponsors according to their rank
- Display logo even with ad-blocker on

2019-12-17 17:18 UTC, Idotno-1 commented
Preview:
![image](https://user-images.githubusercontent.com/34349557/71018867-92cbd980-20f9-11ea-9873-34af168a552e.png)

2019-12-17 18:58 UTC, seirl requested changes

2019-12-17 18:58 UTC, seirl commented on prologin/news/migrations_zinnia/0003_auto_20191212_1705.py
> +# Generated by Django 2.2.8 on 2019-12-12 16:05
What is this?!

2019-12-17 18:58 UTC, seirl commented on prologin/prologin/static/css/prologin.css
> +.partenaire-logo {
Please don't translate our code to french :-)

2019-12-17 18:58 UTC, seirl commented on prologin/sponsor/templates/sponsor/index.html
> +        <a href="{% static 'sponsor/brochures/sponsors_fr_2020.pdf' %}">
Where is that file coming from?

2019-12-20 14:15 UTC, AurelReb commented on prologin/prologin/static/css/prologin.css
> +.partenaire-logo {
indeed, I'll change it to `spons-logo`

2019-12-20 14:16 UTC, AurelReb commented on prologin/sponsor/templates/sponsor/index.html
> +        <a href="{% static 'sponsor/brochures/sponsors_fr_2020.pdf' %}">
oups, seems I didn't push the files in the static documents

2019-12-20 18:48 UTC, Idotno-1 commented on prologin/news/migrations_zinnia/0003_auto_20191212_1705.py
> +# Generated by Django 2.2.8 on 2019-12-12 16:05
This file was generated after I ran `makemigrations`, thus I guessed it was useful. Removing it causes a warning when wanting to `migrate`.

> _Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them._

2020-01-12 17:14 UTC, zopieux commented on prologin/news/migrations_zinnia/0003_auto_20191212_1705.py
> +# Generated by Django 2.2.8 on 2019-12-12 16:05
Ignore the warning or investigate why this is happening. This has nothing to do in this PR.

2020-01-12 17:21 UTC, zopieux requested changes

2020-01-12 17:21 UTC, zopieux commented on prologin/sponsor/templates/sponsor/index.html
> +          {% endblocktrans %}
Looks like {% trans %} should be enough.

2020-01-12 17:21 UTC, zopieux commented on prologin/sponsor/templates/sponsor/index.html
> -          </a>
I don't get it. Just put that out of the loop? Same for the `</div>`.

2020-01-12 17:21 UTC, zopieux commented on prologin/sponsor/templates/sponsor/index.html
> +              <img alt="{{ sponsor.name }}" src="{{ sponsor.logo.url }}" style="max-width:100%; max-height: 10em;" />
This goes into a CSS class.

2020-01-12 17:21 UTC, zopieux commented on prologin/sponsor/views.py
> +        context['language'] = translation.get_language()
Remove this. You can get the current language code directly in the template.

2020-01-12 17:21 UTC, zopieux commented on prologin/sponsor/views.py
> +        context['sponsors_gold'] = [x for x in sponsors if x.rank_significance == 90]
Any way you could use the name instead of this random number that is only used for ordering? Rank is an enum, that gives you a nice Python symbol to reuse.

2020-02-06 12:57 UTC, Idotno-1 commented on prologin/sponsor/templates/sponsor/index.html
> -          </a>
In case there were no longer a sponsor in a category, this would prevent having an empty section with a title.

2020-02-06 13:01 UTC, seirl commented on prologin/sponsor/templates/sponsor/index.html
> -          </a>
Then use `{% if sponsors_gold %}` above the loop maybe?

2020-02-25 18:47 UTC, AurelReb commented on prologin/sponsor/views.py
> +        context['sponsors_gold'] = [x for x in sponsors if x.rank_significance == 90]
Not sure to understand what you want.

2020-02-27 00:00 UTC, Zopieux commented on prologin/sponsor/views.py
> +        context['sponsors_gold'] = [x for x in sponsors if x.rank_significance == 90]
Tu utilises des [nombres magiques](https://fr.wikipedia.org/wiki/Nombre_magique_(programmation)) à deux endroits (`models.py` et `views.py`), je demande si ce serait pas mieux d'avoir un enum ou des constantes Python pour ces nombres, que tu déclares une seule fois dans `models.py` et que tu réutilises ici et dans le `choices=`.

2020-02-27 00:15 UTC, AurelReb commented on prologin/sponsor/views.py
> +        context['sponsors_gold'] = [x for x in sponsors if x.rank_significance == 90]
Ah oui ok, en effet c'est une bonne idée de faire un enum pour ça.

2020-03-10 15:08 UTC, AurelReb commented
I think everything is done. How can I add translations to the template?

2020-03-10 15:13 UTC, seirl requested changes

2020-03-10 15:13 UTC, seirl commented on .gitignore
> +.venv/
Not related to this PR, you can either do a separate commit or add that in your .git/info/exclude

2020-03-10 15:13 UTC, seirl commented on .gitignore
> +.vscode/
This should definitely go in your .git/info/exclude

2020-03-10 15:13 UTC, seirl commented on prologin/sponsor/models.py
> +from prologin.utils.db import CaseMapping
Sort these imports, you're importing two times from models and two times from utils

2020-03-10 15:13 UTC, seirl commented on prologin/sponsor/models.py
> +
Remove

2020-03-10 15:13 UTC, seirl commented on prologin/sponsor/templates/sponsor/index.html
> +    {% for sponsor in sponsors_gold %}
Is there a reason why you have three almost identical loops instead of looping over all the possible ranks in order of importance? If the style of the sections differ, could this maybe be changed in the CSS?

2020-03-10 15:13 UTC, seirl commented on prologin/sponsor/templates/sponsor/index.html
> +    {% endif %}
Put the entire for in the if to avoid redoing the if after the loop

2020-03-10 15:13 UTC, seirl commented on prologin/sponsor/views.py
> +
nit: PEP8 recommends to use spacing inside functions sparingly.

2020-03-10 15:15 UTC, seirl commented
Thanks! This looks a lot better. I'm still not sure I'm fully on board with having the plaquette committed in the website instead of being an asset in media/ though. Otherwise, a few nitpicks here and there, but this is pretty good.

2020-03-10 16:19 UTC, AurelReb commented on prologin/sponsor/templates/sponsor/index.html
> +    {% for sponsor in sponsors_gold %}
I agree for the silver and bronze loops, but as the gold loop includes other HTML elements, I don't think I can merge it with the other loops :/

2020-03-10 16:56 UTC, AurelReb commented on prologin/sponsor/templates/sponsor/index.html
> +    {% for sponsor in sponsors_gold %}
Also I don't know how to change the title "Silver" or "Bronze" in the template and translate them directly in the loop

2020-03-12 21:46 UTC, zopieux reviewed
Looks good. Please fix the latest comments.

2020-03-12 21:46 UTC, Zopieux commented on prologin/sponsor/models.py
> +from prologin.utils.db import CaseMapping
Or, just use less direct imports: `BooleanField` → `models.BooleanField` and drop that import line.

2020-03-30 17:41 UTC, AurelReb commented on prologin/sponsor/templates/sponsor/index.html
> +    {% for sponsor in sponsors_gold %}
Is it good, or is it really needed before merging this PR?

2020-04-14 10:39 UTC, seirl approved these changes

2020-04-14 13:47 UTC, merged