Gdpr compliance
prologin/concours-site pull request #246
Opened 2020-02-05 22:23 UTC by AurelReb

Add GDPR page and inform users about their privacy.
#230

2020-02-06 12:58 UTC, seirl commented
Random idea: maybe all that legalese could go directly in a markdown file? It's just a generic self-contained text with no interaction to the rest of the site.

2020-02-09 16:30 UTC, cyril-amar requested changes

2020-02-09 16:30 UTC, O-Xian commented on prologin/pages/templates/pages/about-privacy-policy.html
> +            être contacté directement </p>
Missing text at the end:
```suggestion
            être <a href="mailto:info@prologin.org">contacté directement</a> pour demander une évaluation manuelle.  </p>
```

2020-02-09 16:32 UTC, O-Xian commented
> 
> 
> Random idea: maybe all that legalese could go directly in a markdown file? It's just a generic self-contained text with no interaction to the rest of the site.

Why not, it's not like we will need to update it frequently.

2020-03-11 19:24 UTC, cyril-amar approved these changes
Fixed typos in both .po and privacy policy.

2020-03-11 20:05 UTC, merged

2020-03-11 20:36 UTC, seirl commented
I removed this from master. Please don't push until you get a review from the site's maintainers.

2020-03-11 20:42 UTC, seirl commented on .gitignore
> +.venv/
This shouldn't be in this diff.

2020-03-11 20:42 UTC, seirl commented on prologin/pages/templates/pages/about-privacy-policy.html
> +{% blocktrans %}
Don't have so much HTML in a blocktrans.

Use `{% blocktrans asvar ...` with markdown inside, then use a markdown filter.

2020-03-11 20:42 UTC, seirl commented on prologin/users/templates/users/edit.html
> +  <small>Je consens au traitement de mes données personnelles ci-dessus par Prologin.</small>
French?

2020-03-11 20:42 UTC, seirl commented on prologin/users/templates/users/edit.html
> +      Prologin est organisés par l'association Prologin, qui agit en tant que contrôleur de données. Les réponses collectées dans ce formulaire nous permettent de fournir les services (communication
French?

2020-03-11 20:42 UTC, seirl commented on prologin/users/templates/users/register.html
> +    <small class="col-sm-offset-2 col-sm-10">Je consens au traitement de mes données personnelles ci-dessus par Prologin.</small>
French?

2020-03-11 20:42 UTC, seirl commented on prologin/users/templates/users/register.html
> +      Prologin est organisés par l'association Prologin, qui agit en tant que contrôleur de données. Les réponses collectées dans ce formulaire nous permettent de fournir les services (communication
French?