final2020: change displayed date to temporary text
prologin/concours-site pull request #255
Opened 2020-04-07 19:13 UTC by Elfikurr

Hello,

This PR is here because of the current sanitary events and the discrepancy between what we announced and what is displayed on the website.

It is a temporary hot fix to prevent people from thinking the final will go on as planned initially.
I believe there is no other reference to the final's date on the website, apart from the /about/contest/final, which we could change, but since we don't have a date at the moment, it doesn't make a lot of sense to do it.

2020-04-07 20:27 UTC, zopieux requested changes

2020-04-07 20:27 UTC, Zopieux commented on prologin/homepage/templates/homepage/jumbotron-final.html
> -          {{ final.date_begin|date:"d b Y"|default:no_such_date }}
Use a Django comment `{# #}`

2020-04-13 00:42 UTC, Elfikurr commented
Since the final Event was removed, is this still useful ?
@haltode said he still wanted this, but I do not remember.

2020-04-13 14:12 UTC, Zopieux commented
The diff LGTM, but please do not merge if we realize we don't need it.

I'd argue for hardcoding a banner in the home template though.

2020-04-13 14:12 UTC, zopieux approved these changes

2020-04-14 18:01 UTC, haltode requested changes

2020-04-14 18:01 UTC, haltode commented on prologin/homepage/templates/homepage/homepage.html
> +    <strong>{% trans 'Due to the sanitary crisis, the final date will be announced later. Please read the news for more information.' %}</strong>
"read the news" is a bit vague, this should point to the specific Prologin news: https://prologin.org/news/2020/03/29/prologin-2020-et-le-coronavirus-2019/

2020-04-20 13:25 UTC, Elfikurr commented
Can we merge that ?

2020-04-20 15:49 UTC, merged