finale2020: adding rule to show final download button or not
prologin/concours-site pull request #257
Opened 2020-04-10 18:47 UTC by Elfikurr

2020-04-10 18:50 UTC, zopieux requested changes

2020-04-10 18:50 UTC, Zopieux commented on prologin/documents/rules.py
>              contestant.assignation_final == contest.models.Assignation.assigned.value)
Est-ce que tu peux faire en sorte que ton check d'existence soit inclu dans `contestant.assignation_final`? Idéalement y'aura rien à changer dans `rules.py`.

2020-04-10 18:50 UTC, Zopieux commented on prologin/documents/rules.py
> +rules.add_perm('documents.user_can_download_final', can_download_final)
C'est pas déjà ce que fait `generate_final_contestant_document` ?

2020-04-12 15:06 UTC, Elfikurr commented on prologin/documents/rules.py
>              contestant.assignation_final == contest.models.Assignation.assigned.value)
Je pensais utiliser `contestant.is_assigned_for_final`, mais du coup ça change le stud-semifinal-result.html...
Ou alors tu voulais rajouter un autre champ dans `contestant.assignation_final` ?
Ne vaudrait il pas mieux utiliser les fonctions `contestant.is_assigned_for_final` et `contestant.is_assigned_for_semifinal` dans le `rules.py` ?

2020-04-12 15:07 UTC, Elfikurr commented on prologin/documents/rules.py
> +rules.add_perm('documents.user_can_download_final', can_download_final)
C'est vrai, c'est le `rules.is_staff | can_download_final` qui me dérangeait : le staff pourrait quand même cliquer sur le bouton, mais c'est pas trop grave je suppose !

2020-04-12 16:42 UTC, seirl commented on prologin/homepage/templates/homepage/jumbotron-final.html
> +          {% has_perm 'documents.generate_final_contestant_document' request.user contestant as user_can_download_final %}
Maybe this check should only be for the "Download paperwork" link, instead of the whole thing?

2020-04-12 16:45 UTC, Elfikurr commented on prologin/homepage/templates/homepage/jumbotron-final.html
> +          {% has_perm 'documents.generate_final_contestant_document' request.user contestant as user_can_download_final %}
I did this because, if I'm not mistaken, the `The final will take place at:` block has no date nor center if there is no final Event.

2022-07-31 14:57 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/257

2022-07-31 14:57 UTC, closed without merging