about-gcc: adding gcc description in the about-organization page
prologin/concours-site pull request #258
Opened 2020-04-12 16:30 UTC by Elfikurr

Closes #250 

Hello,

This PR simply adds a Girls Can Code! description with a link to the Girls Can Code! website on the `about-organization` page.

Feel free to update, correct or improve the description if needed.

Thanks in advance for your reviews.

2020-04-13 14:20 UTC, zopieux requested changes

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +algorithms, explore numerous material such as network, web development, robotics, microcontrollers, video games
s/material/CS topics/ or something

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +{% blocktrans %}<p class="text-justify">Prologin started to organize in 2014 the Girls Can Code! summer camps.
In 2014, Prologin …

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +to exchange with women working in the computer science industry or in research fields. The young girls are sometimes,
s/or in research fields/or acadamia/ maybe?

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +to exchange with women working in the computer science industry or in research fields. The young girls are sometimes,
extraneous trailing comma

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +unsure as to what they want to do, this is a golden occasion for them to discuss with the speaker their educational
missing "about" or some glue word after "discuss with"

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +<p class="text-justify">Prologin's members are present during the camp to accompany them and to help them debug their
*Prologin staff is present*

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +<p class="text-justify">Prologin's members are present during the camp to accompany them and to help them debug their
Too many *and*s. Use the form "x, y and z".

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +<p class⁼"text-justify">More information can be found on Girls Can Code! <a href="https://gcc.prologin.org">website</a>. For any
Include GCC in the link

2020-04-13 14:20 UTC, Zopieux commented on prologin/pages/templates/pages/about-organization.html
> +inquiries, please contact us <a href="{{ about_organization }}#contact">here</a>.</p>{% endblocktrans %}
please [contact us].

2020-04-14 09:06 UTC, fnareoh requested changes
I approve the English content but I would like to check the translation before approving for merging. Thank you for your work, it really needed to be added !

2020-04-30 19:45 UTC, fnareoh approved these changes

2020-09-11 21:29 UTC, Elfikurr commented
I'll merge this soon, and I'll update the translation on Transifex when doing so.

2020-09-13 12:45 UTC, merged