html-formatting-admin: adding format_html in /prologin/utils/__init__.py
prologin/concours-site pull request #261
Opened 2020-04-13 00:39 UTC by Elfikurr

Fixes #183 

Hello,

This PR simply adds the `format_html` function to `admin_url_for`.

Thank you.

2020-04-13 14:15 UTC, zopieux requested changes
Beyond fixing my comment, can you explain the rationale of the PR instead of explaining what it does (this part I know by reading the code)?

2020-04-13 14:15 UTC, Zopieux commented on prologin/prologin/utils/__init__.py
> +    return format_html('<a href="{}">{}</a>'.format(reverse('admin:{}_{}_{}'.format(obj._meta.app_label, obj._meta.model_name, method),
The goal of this function is precisely to avoid relying on Python's built-in `format` to build safe HTML: https://docs.djangoproject.com/en/2.2/ref/utils/#django.utils.html.format_html

2020-04-13 14:54 UTC, Elfikurr commented on prologin/prologin/utils/__init__.py
> +    return format_html('<a href="{}">{}</a>'.format(reverse('admin:{}_{}_{}'.format(obj._meta.app_label, obj._meta.model_name, method),
Is this better now ?

2020-04-17 12:18 UTC, seirl approved these changes

2020-09-11 20:29 UTC, Elfikurr commented
@Zopieux is this ok for you ?

2020-09-13 12:54 UTC, merged