sponsors: fix alignment for silver and bronze ranks
prologin/concours-site pull request #264
Opened 2020-04-14 21:48 UTC by AurelReb

this PR fixes the alignment of logos for bronze and silver ranks

2020-04-21 10:34 UTC, haltode requested changes

2020-04-21 10:34 UTC, haltode commented on prologin/sponsor/templates/sponsor/index.html
> +        {% endif %}
There is already a condition for Gold/others right below these lines, it would be better to regroup it all together.

2020-04-21 10:34 UTC, haltode commented on prologin/prologin/static/css/prologin.css
> +@media (min-width: 992px) {
Is this an intentional change? Seems like a hack or a test pushed by error.

2020-04-21 10:37 UTC, AurelReb commented on prologin/prologin/static/css/prologin.css
> +@media (min-width: 992px) {
992px is the md breakpoint in bootstrap. So this is intentional to keep responsiveness.

2020-04-21 10:41 UTC, haltode commented on prologin/prologin/static/css/prologin.css
> +@media (min-width: 992px) {
Ok, can you add a comment above to explain this magic number then?

2020-04-21 10:47 UTC, AurelReb commented on prologin/sponsor/templates/sponsor/index.html
> +        {% endif %}
The condition below these lines is into a `for` loop. Therefore, I can't regroup it all together.

2020-09-02 18:18 UTC, Elfikurr commented
@seirl @Zopieux can we merge this ?

2020-09-03 20:08 UTC, seirl approved these changes

2020-09-03 20:26 UTC, merged