Forum delete url
prologin/concours-site pull request #268
Opened 2020-04-17 00:57 UTC by Elfikurr

Fixes #197 

Hello,

This PR changes the success URL after deleting a thread, which is no longer the thread's, but rather the forum's itself to prevent a 404 error for the user.

Thank you.

2020-04-18 16:03 UTC, AurelReb approved these changes

2020-04-21 21:44 UTC, zopieux requested changes
Just a few things to change, then it's good.

2020-04-21 21:44 UTC, Zopieux commented on prologin/forum/models.py
> +    def delete(self, using=None):
`delete` returns stuff. Please respect the overridden API:
```python
def delete(self, **kwargs):
  if self.is_tread_head:
    # A thread with its original first post deleted makes no sense, so delete
    # the thread itself when its first (head) post is deleted.
    return self.thread.delete(**kwargs)
  return super().delete(**kwargs)
```

2020-04-21 21:44 UTC, Zopieux commented on prologin/forum/tests.py
> +        self.assertRedirects(page, f"/forum/test-forum-1/tout-est-casse-{self.t11.pk}/")
Thanks! Didn't know about that shortcut.

2020-04-21 21:44 UTC, Zopieux commented on prologin/forum/tests.py
>          page = self.client.get(url)
Inline `url`

2020-04-21 21:44 UTC, Zopieux commented on prologin/forum/views.py
> +        # there is only one post remaining or it's the thread head
To be honest it's not supposed to happen that the only remaining post is something else that the head post… I'd only keep is_thread_head condition. We can always do some offline cleanups.

2020-04-21 22:03 UTC, Elfikurr commented on prologin/forum/models.py
> +    def delete(self, using=None):
Thanks, I forgot about this.
Could you tell me where you found the delete function prototype ?
In the models.Model I find : `delete(self, using=None, keep_parents=False)`, but since it doesn't match what you wrote, I'm confused as to why it is `delete(self, **kwargs)`, and without `*args`.

2020-09-11 20:58 UTC, Elfikurr commented
I just changed the str.format to f strings
And I tested it again, and it looks good.

When deleting a post, we are redirected to the thread.
If this post was the thread head (the first post of the thread) then we redirect the user to the forum page, avoiding a 404.

@Zopieux do you have something else to add ?

2020-09-13 13:07 UTC, merged