Fix qcm answers are not shown when correcting (Fix #324)
prologin/concours-site pull request #328
Opened 2021-02-09 23:37 UTC by e-n-0

2021-02-13 16:55 UTC, Nhqml approved these changes
Ok pour moi, c'est moche mais ça marche

2021-02-14 16:39 UTC, e-n-0 commented
C'est maintenant moins moche.
Petit changement: Ca affiche en vert les bonnes réponses même si elles n'ont pas été sélectionnées. Ca supporte aussi les questions de qcm où il peut exister plusieurs réponses possible pour une question.

2021-02-14 17:57 UTC, Elfikurr requested changes
Please remove "correction_mode" from the associated view, since it is no longer used.
I thought we could fix the way it was designed at first, but it's okay this way too !

2021-02-14 18:34 UTC, Elfikurr approved these changes

2022-07-31 14:57 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/328

2022-07-31 14:57 UTC, closed without merging