Fix user can be born in the future (#327)
prologin/concours-site pull request #329
Opened 2021-02-09 23:40 UTC by e-n-0

2021-02-11 21:17 UTC, Nhqml approved these changes

2021-02-11 21:37 UTC, Elfikurr commented
I believe that `clean()` should raise a `ValidationError` when encountering an error ?
Especially if there is only one error, else we should use `add_error()` instead of `self.error_class`, if I'm reading the docs (badum tss) correctly.

2021-02-11 21:41 UTC, lportemo requested changes
Why can't you just use a validator on the model ?

2021-02-11 21:41 UTC, lportemo commented on prologin/users/forms.py
> +        if birthday and birthday > datetime.today().date():
isn't there any warning about using datetime.today().date() instead of timezone.now().date() ?

2021-02-14 15:05 UTC, e-n-0 commented on prologin/users/forms.py
> +        if birthday and birthday > datetime.today().date():
Using user's timezone is maybe better.

2021-02-14 15:14 UTC, Nhqml commented
IMO, the use of validators as suggested by @lportemo is a cleaner way to achieve our goal. It will also be more consistent if we decide to implement more validations steps in the future.

I believe we should instead focus on #331. Feel free to reopen this if you disagree.

2021-02-14 15:14 UTC, closed without merging