SearchBar for Forum
prologin/concours-site pull request #342
Opened 2021-02-19 10:46 UTC by MrThimote

Search for a special Thread in a Forum by name
https://github.com/prologin/site/issues/341
![image](https://user-images.githubusercontent.com/58882120/108494574-fe827700-72a7-11eb-8b85-2484d4626fd1.png)
Might need some adjustement on CSS

2021-02-19 11:58 UTC, MrThimote commented
One possible Bug in the Program :
let's assume we have two forums, a forum contains an id, a name and a slug, the program only takes the slug to get the forum, if there are two forums with the same slugs but not the same id, a bug might appear.

2021-02-22 20:23 UTC, MrThimote commented
Bug of Forum with same Names fixed,
I modified the entire search according to Elfikur's request, when you press Enter in the text box to search, it will send you on a page of this form "/forum/search/forum-slug-id?q=Your query" and will show all the pages which have been requested on the page number 1. There is also a variable of the ForumSearchSuggestView called context_query_render_type, which is a boolean and if True the query will be written in the text box but if false there will be a text below the search bar.
Possible bug that I will fix is to verify whether the form of the url is correct cause for the moment, if there is no query/no ?q=, redirect to the "/forum/forum-slug-id"

2021-02-22 20:59 UTC, lportemo requested changes

2021-02-22 20:59 UTC, lportemo commented on prologin/forum/templates/forum/base.html
> +    function urlSplitFromLocation() {
Use an html django/html form instead of this trick to submit. Your form might be like `<form method="GET" action="{% url 'forum:my-page' %}"`

2021-02-22 20:59 UTC, lportemo commented on prologin/forum/static/js/thread-search.js
> +})();
Do not use JS, just use an html form

2021-02-22 20:59 UTC, lportemo commented on prologin/forum/views.py
> +        return super().get(request, *args, **kwargs)
Can you elaborate on this ?

2021-02-22 20:59 UTC, lportemo commented on prologin/prologin/static/css/prologin.css
> +  width: 100% !important;
Try not to use `!important`

2021-02-22 20:59 UTC, lportemo commented on prologin/forum/views.py
> +        context['queryrendertype'] = self.context_query_render_type
This part is not relevant, the content of the search should always be displayed to the user.

2021-02-22 20:59 UTC, lportemo commented on prologin/forum/views.py
> +        }
Do not try to parse yourself the URL, django has a battle-tested mechanism to do that, You should use a variable corresponding to the slug and id in you urls.py

2021-02-22 20:59 UTC, lportemo commented on prologin/forum/urls.py
> +    path('search/<forum_name>', views.ForumSearchSuggestView.as_view(), name='search-thread'),
See comment below

2021-02-22 20:59 UTC, lportemo commented on prologin/forum/views.py
> +from django.template.loader import render_to_string
AFAIK this is an unused import

2021-02-22 21:48 UTC, MrThimote commented on prologin/forum/views.py
> +        context['queryrendertype'] = self.context_query_render_type
The content of the search is always displayed, i might have said it the wrong way, when it is true, the search is in the input field in which it was placed before the query and if false the search bar will be blank and there will be some place in which there will be written results for query query. As I didn't knew what was the best way for a user experience, i have made it so that it can be modified just by modifyng a variable

2021-02-23 09:45 UTC, lportemo requested changes

2021-02-23 09:45 UTC, lportemo commented on prologin/forum/views.py
> +        context['url_search'] = "/forum/search/" + self.kwargs['slug'] + "-" + self.kwargs["pk"]
You may use django.urls.reverse or django.urls.reverse_lazy to construct the URL in a more correct way

2021-02-23 09:45 UTC, lportemo commented on prologin/forum/views.py
> +        context['url_search'] = "/forum/search/" + self.kwargs['slug'] + "-" + self.kwargs["pk"]
you may use the `{% url %}` templatetag directly in your template (https://docs.djangoproject.com/fr/3.1/ref/templates/builtins/#url) instead of manually building the url

2021-02-23 09:45 UTC, lportemo commented on prologin/forum/views.py
> +        context['url_search'] = "/forum/search/" + self.kwargs['slug'] + "-" + self.kwargs["pk"]
Arguments for reverse are the same than arguments for reverse/reverse_lazy

2021-02-23 09:45 UTC, lportemo commented on prologin/forum/views.py
>              return redirect('forum:forum', slug=forum.slug, pk=forum.pk)
I guess you can use only one condition for this :)

2021-02-23 09:45 UTC, lportemo commented on prologin/forum/views.py
>          context['query'] = self.request.GET.get('q', '').strip()
You already checked that `self.request.GET['q']` exists in the your_view.get method, as the get_context_data is executed after the your_view.get() method, you can just use self.request.GET['q']

2021-02-23 09:45 UTC, lportemo commented on prologin/forum/templates/forum/forum_threads.html
> +  <form class="form-inline form-user-search" action="{{ url_search }}">
see comments below (related to url_search in get_context_data)

2021-02-23 09:45 UTC, lportemo commented on prologin/forum/templates/forum/forum_threads.html
> +      <input value="{{ query }}" id="search-thread-name" name="q" type="text" autocomplete="off" class="form-control" placeholder="{% trans "Search thread" %}">
Not sure, but I think the if is not necessary there, you can just put value={{ variable }} if a variable is None I guess it will print nothing, if it prints None you may use the default (https://docs.djangoproject.com/fr/3.1/ref/templates/builtins/#default) or default_is_none filter in your query variable.

Not really important tho, do not apply this if it breaks the placeholder ;)

2021-02-23 09:45 UTC, lportemo commented on prologin/forum/models.py
> +
If you are changing the indexes you must run `./manage.py makemigrations` and commit the migrations files

2021-02-23 14:03 UTC, lportemo commented
@MrThimote : you may remove the zinnia migration. It seems good to me. I'll be testing this on a dev environment soon before merging it. Thanks for your work and your quick responses to this PR :)

2021-02-23 14:14 UTC, MrThimote commented
ok i just have a question how do i remove this file do i just delete it and push again and this will work or do i need to do something special so that it works?

2021-02-23 14:15 UTC, lportemo commented
You just need to delete the file, git add the deleted file , git commit and git push 🙂

2021-02-23 14:20 UTC, MrThimote commented
Ok, thank you

2022-07-31 14:56 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/342

2022-07-31 14:56 UTC, closed without merging