dev_forumtification: added backend for notification system
prologin/concours-site pull request #345
Opened 2021-02-27 00:21 UTC by MrThimote

Beggining of work for the #294 issue, added backend code to calculate notifications for subscribed threads.

2021-02-27 17:20 UTC, MrThimote commented
Actual Look of the System : 
When there is no notifications :
![image](https://user-images.githubusercontent.com/58882120/109394537-d211cf00-7927-11eb-9fa2-1b49c6ec8426.png)
Notification with one message : 
![image](https://user-images.githubusercontent.com/58882120/109394603-26b54a00-7928-11eb-9bae-a841023a7447.png)
Notification with two :
![image](https://user-images.githubusercontent.com/58882120/109394628-43ea1880-7928-11eb-9822-cb8babb4ca4a.png)
Notification with three or more : 
![image](https://user-images.githubusercontent.com/58882120/109394648-5bc19c80-7928-11eb-8847-05cb6994c48c.png)

2021-02-27 17:33 UTC, MrThimote commented
And the look of the subscribe to a thread part (might need an adjustement for the image cause i haden't any to pick)
Unsubscribe :
![image](https://user-images.githubusercontent.com/58882120/109394967-2c139400-792a-11eb-9630-ccb7f82848fb.png)
Subscribe : 
![image](https://user-images.githubusercontent.com/58882120/109394994-49486280-792a-11eb-8f82-1f0933506dc9.png)

2021-04-30 09:39 UTC, lportemo requested changes
Thanks for the PR, I think there should be a total rework of your models. They seem too complex.

For instance, I don't see the point of the NotificationList model, you may just filter notifications by user and get the len of the queryset to get the notification_count.

You are using .filter()[0] to get a single element from db, you may use instead the .get() method of the ModelManager in a try..except ObjectDoesNotExist statement or if you are in a view you may just use [django.shortcuts.get_object_or_404](https://docs.djangoproject.com/fr/3.2/topics/http/shortcuts/#get-object-or-404).

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/migrations/0003_auto_20210226_2307.py
> +    ]
Please squash your migrations

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/models.py
> +        if robj.subtype == 1:
Please avoid magic numbers and use the enum

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/models.py
> +    notification_count = models.PositiveIntegerField(verbose_name=_("Number of notifications"), editable=False, blank=True, default=0)
There's no need for that as you can get that count with notification_list_object.notification.count()

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/models.py
> +        self.save()
IMO this method is not needed

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/models.py
> +        self.notification.save()
IMO this method is not needed

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/models.py
> +    print(notifications)
we don't want worker's stdout to be polluted with this, please remove any prints in your code and use python's logging api if needed

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/templates/forum/thread_posts.html
> +  <form style="display: inline-block" action="{% url 'forum:toggle-subscribe-post' thread.forum.slug thread.forum.pk thread.slug thread.pk %}" method="post" class="form form-inline">
please do not use inline style

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/views.py
> +from forum.models import ReadState,build_notification_list,Notification,NotificationList,Thread
Unnecessary import (see previous line)

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/views.py
> +            context["subscribed"] = (robj.subtype == 1)
Again, please do not use magic numbers, refer to the enum

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/views.py
> +        rs.subtype = (rs.subtype + 1) % 2
Sorry, we don't do that here.

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/views.py
> +        rs = ReadState.objects.filter(user=request.user, thread=thread)[0]
Please, stop doing that filter()[0] thing, in a django view 
 you can use [django.shortcuts.get_object_or_404](https://docs.djangoproject.com/fr/3.2/topics/http/shortcuts/#get-object-or-404) that will raise a 404 error if the object is not found.

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/views.py
> +        return redirect(self.get_success_url())
In the whole function you did not check if the queryset returned by filter() was empty, so again django.shortcuts.get_object_or_404 can help you save a lot of ifs

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/templates/forum/notification.html
> +                    {% blocktrans with username=notif.thread.author.username date_full=notif.thread.date_created|date:"c" date=notif.thread.date_created|date:"DATETIME_FORMAT" %}By <span class="notif
Please rework this the 3-piped date is not understandable

2021-04-30 09:39 UTC, lportemo commented on prologin/forum/views.py
> +        return redirect(self.get_success_url())
What is the template used for this view ?
If you use this view only for POST, don't use a ListView, but just a simple View and implement the post method.

2021-04-30 09:46 UTC, lportemo commented
I also see that you used the `@cached_property` on a method that returns a queryset. You should not do that as it may intefere with the django caching backend.

2022-07-31 14:56 UTC, juli0z commented
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/345

2022-07-31 14:56 UTC, closed without merging