problems: add camisole debug i/o to traces
prologin/concours-site pull request #92
Opened 2017-10-16 00:39 UTC by seirl

2017-10-16 07:27 UTC, zopieux commented
The thing is, what will you do when we finally use webpack instead of JSON? I guess we're better of using `pformat` instead of `json.dumps`, as the message serialization is not relevant and will be obsolete when camisole 1.0 is merged.

2017-10-16 10:22 UTC, zopieux requested changes

2017-10-16 10:22 UTC, zopieux commented on prologin/problems/models/submission.py
> +    return s[:l] + '...' if len(s) > l else s
`…`

2017-10-16 10:22 UTC, zopieux commented on prologin/problems/models/submission.py
> +        return json.dumps(req, sort_keys=True, indent=4)
Use `pformat`

2017-10-16 10:22 UTC, zopieux commented on prologin/problems/models/submission.py
> +        return json.dumps(rep, sort_keys=True, indent=4)
Use `pformat`

2017-10-22 11:32 UTC, zopieux commented on prologin/problems/models/submission.py
> +        Generate a Camisole request for the given SubmissionCode.
**c**amisole

2017-10-22 11:32 UTC, zopieux commented on prologin/problems/models/submission.py
> +    append = b'...' if isinstance(s, bytes) else '...'
what about `…`

2017-10-22 11:40 UTC, seirl commented on prologin/problems/models/submission.py
> +    append = b'...' if isinstance(s, bytes) else '...'
Ugly with bytes

2017-10-22 11:44 UTC, zopieux approved these changes

2017-10-22 11:49 UTC, merged