Fix manual
prologin/concours-site pull request #93
Opened 2017-11-18 15:02 UTC by pguenezan

- update compiler version and args fetching from camisole
- add two documents

2017-11-27 00:31 UTC, seirl requested changes

2017-11-27 00:31 UTC, seirl commented on prologin/documents/templates/documents/index.html
> +              <strong>{% trans "Launch" %}</strong>
Why is this in "Organisation"?

2017-11-27 00:31 UTC, seirl commented on prologin/documents/templates/documents/index.html
> +                <i class="fa fa-envelope"></i> {% trans "Mail to contestant" %}
contestants

2017-11-27 00:31 UTC, seirl commented on prologin/documents/templates/documents/index.html
> +                <i class="fa fa-envelope"></i> {% trans "Mail to school" %}
schools

2017-11-27 00:31 UTC, seirl commented on prologin/documents/urls.py
> +    url(r'^launch-mail-contestant$', documents.views.LaunchMailToContestantView.as_view(), name='launch-mail-contestant'),
Why is this in organization?

2017-11-27 00:31 UTC, seirl commented on prologin/problems/views.py
> +            version = language.get('programs').get(program).get('version')
Why do you use get() if it just crashes when get() returns None?

2017-11-27 00:31 UTC, seirl commented on prologin/problems/views.py
> +            program = list(language.get('programs').keys())[0]
Why do you only take the first compiler? All of them are important.

2017-11-27 20:37 UTC, zopieux requested changes

2017-11-27 20:37 UTC, zopieux commented on prologin/problems/templates/problems/manual.html
> +  {% if args|length != 0 %}
``if args``?

2017-11-27 20:37 UTC, zopieux commented on prologin/problems/templates/problems/manual.html
> +{% endfor %}
Okay so you get this from `/languages`:
```json
 "brainfuck": {
            "name": "Brainfuck",
            "programs": {
                "esotope-bfc": {
                    "opts": [],
                    "version": null
                },
                "gcc": {
                    "opts": [
                        "-std=c11",
                        "-Wall",
                        "-Wextra",
                        "-O2",
                        "-lm"
                    ],
                    "version": "7.2.0"
                },
                "python2": {
                    "opts": [
                        "-S",
                        "/usr/sbin/esotope-bfc",
                        "-v",
                        "-fc"
                    ],
                    "version": "2.7.14"
                }
            }
        },
```
so eg. for Brainfuck we want this:

>Brainfuck:
>  * esotope-bfc
>  * gcc 7.2.0 with `-std=c11 -Wall -Wextra -O2 -lm`
>  * python2 2.7.14 with `-S /usr/bin/esotope-bfc -v -fc`

2018-01-31 18:32 UTC, zopieux commented
Please split the mailing stuff in a new PR, as the training manual stuff was superseded by 324bcac.

2018-01-31 18:32 UTC, closed without merging