Add a delete view
prologin/concours-site pull request #98
Opened 2018-03-05 13:27 UTC by fnareoh

Right now there is only a button delete on the user profile and not when you edit your profile which migth be a bit counter intuitive.
The position of the delete button is  a bit ugly.
The code forbids from deleting the account when the contest is on as mentioned in #95 .

2018-03-05 13:30 UTC, fnareoh commented
"More red please!"
Sorry,I don't see what you mean ?

2018-03-05 13:35 UTC, seirl commented
A few comments on the view itself:

- I'd like to have a list of things that will be deleted ("this will delete all your personal informations, your XXX, etc") in bold as a warning
- Would it be possible to ask the password for confirmation?

2018-03-05 13:39 UTC, zopieux commented
@seirl [re: list of related stuff going to be deleted] this is a bit involved but it can be done by using [internal Django APIs](https://stackoverflow.com/a/26808663).

2018-03-06 20:05 UTC, seirl commented on prologin/users/templates/users/edit.html
> +  <a href="{% url 'users:delete' user.id %}" class="btn btn-danger">
`edited_user.id`

2018-03-06 20:05 UTC, seirl commented on prologin/users/templates/users/edit.html
> +	  <h1 style = "color: #d9534f;"> <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
class + put this in .css

2018-03-06 21:11 UTC, zopieux requested changes
tl;dr use a `FormView` instead

2018-03-06 21:11 UTC, zopieux commented on prologin/users/templates/users/edit.html
> +	  <h1 style = "color: #d9534f;"> <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
the icon is too big for my taste

2018-03-06 21:11 UTC, zopieux commented on prologin/users/templates/users/edit.html
> +	</div>
whitespaces seem off

2018-03-06 21:11 UTC, zopieux commented on prologin/users/templates/users/edit.html
> +  <p>{% trans "This will delete all your personnal informations, all your posts on the forum and all the code you have submited." %}</p>
isn't “information” a plural singular?

2018-03-06 21:11 UTC, zopieux commented on prologin/users/views.py
> +        return render(self.request, 'users/delete.html', {
Just use a `FormView`?

2018-03-06 21:11 UTC, zopieux commented on prologin/users/views.py
> +        if form.is_valid():
Yeah, definitely use a `FormView` :-)

2018-03-06 21:11 UTC, zopieux commented on prologin/users/views.py
> +            print(user.password)
Thanks but no thanks

2018-03-06 21:11 UTC, zopieux commented on prologin/users/views.py
> +                    is_contest = (self.request.current_edition.is_active
This whole conditional should be computed in the `Edition` model class. Add it if is does not exist yet. Something like `qualification_finished(self)`

2018-03-06 21:11 UTC, zopieux commented on prologin/users/views.py
> +                messages.error(request, "Please enter a correct password.")
Use a proper form error, not a message. To do so, raise `ValidationError` in a [`clean`](https://docs.djangoproject.com/fr/2.0/ref/forms/validation/) method of the `PasswordConfirmForm`.

2018-03-06 21:11 UTC, zopieux commented on prologin/users/views.py
> +                    user.delete()
Put that in your `FormView` `form_valid(self)` handler. Add a call to `logout()` before deleting.

We'll later add a signal to display a staff alert somewhere.

2018-03-07 08:36 UTC, fnareoh commented on prologin/users/views.py
> +                messages.error(request, "Please enter a correct password.")
How can I access the user in the `clean` method of the form to execute `user.check_password(password)` ? I have tried to defined an `__init__` method [inspired by this](https://stackoverflow.com/questions/5119994/get-current-user-in-django-form) but so far I can't make it work.

2018-03-07 08:56 UTC, zopieux commented on prologin/users/views.py
> +                messages.error(request, "Please enter a correct password.")
You're right, it could work but I don't like putting stateful stuff in the form. While Googling I found [this](https://simpleisbetterthancomplex.com/tutorial/2016/08/15/how-to-create-a-password-confirmation-view.html). It's clean, does exactly what we want, uses modern Django stuff and even gives a nice decorator to add the mechanism to any view.

2018-03-07 08:57 UTC, fnareoh commented on prologin/users/views.py
> +                    is_contest = (self.request.current_edition.is_active
Done, I have also replaced it in the `EditUserView`.

2018-03-07 09:08 UTC, zopieux commented on prologin/users/views.py
> +                    is_contest = (self.request.current_edition.is_active
Neat!

2018-03-08 00:27 UTC, zopieux commented
For super users deleting others, please add a "recopy username to delete here" field. That mean you could do a generic confirm page (view) taking any Form class as a class attribute, one for users deleting self, one for SU. Two views (and two forms, one for each) both inheriting a third, generic Confirm view.

2018-03-08 14:16 UTC, seirl requested changes

2018-03-08 14:16 UTC, seirl commented on prologin/users/views.py
> +        kwargs['user'] = self.request.user
Do you really need this? It's already `{{ request.user }}`

2018-03-08 14:16 UTC, seirl commented on prologin/users/views.py
> +                "You can't delete your account during the contest if you really want to, please send an email to info@prologin.fr"
Two sentences

2018-03-08 14:16 UTC, seirl commented on prologin/users/views.py
> +                             delete_username + " account has been succesfuly deleted")
successfully

2018-03-08 14:16 UTC, seirl commented on prologin/contest/models.py
> +    def qualification_finished(self):
This is really weird. The function is called "qualification_finished" but what it actually checks is whether the current user has the permission to edit its profile. Plus, this has nothing to do in the Edition model.

2018-03-08 14:16 UTC, seirl commented on prologin/users/forms.py
> +
Remove

2018-03-08 14:16 UTC, seirl commented on prologin/users/forms.py
> +        if user.is_staff:
`if user != self.request.user` would probably be more appropriate here?

2018-03-08 14:16 UTC, seirl commented on prologin/users/templates/users/confirm_password.html
> +{% endblock %}
Newline at end of file

2018-03-08 14:16 UTC, seirl commented on prologin/users/templates/users/confirm_password.html
> +{% extends 'prologin/base.html' %}
Shouldn't that file be removed?

2018-03-08 14:16 UTC, seirl commented on prologin/users/views.py
> +                             delete_username + " account has been succesfuly deleted")
and `'s account`

2018-03-08 14:16 UTC, seirl commented on prologin/users/views.py
> +class DeleteView(PermissionRequiredMixin, UpdateView):
Do we really want an UpdateView here? We're not updating anything. I fear it might silently update some fields of the user.

2018-03-08 14:16 UTC, seirl commented on prologin/users/views.py
> +            return render(self.request, 'users/delete.html', context)
I really think you shouldn't do that by hand, the form should be able to do that by itself.

2018-03-08 14:16 UTC, seirl commented on prologin/users/views.py
> +        except KeyError:
What is this supposed to catch? Only use try: except: around the relevant parts

2018-03-08 14:35 UTC, fnareoh commented on prologin/users/views.py
> +        kwargs['user'] = self.request.user
I need it to init the form and have a user_confirm field field only if the user is_staff

2018-03-08 14:40 UTC, fnareoh commented on prologin/contest/models.py
> +    def qualification_finished(self):
[zopieux told me to do so](https://github.com/prologin/site/pull/98/files/b497894d051e123152deca5de5592a2c367014b3#diff-179adfdfcc0692485b7637aa929677c2)

2018-03-08 14:44 UTC, fnareoh commented on prologin/users/views.py
> +        except KeyError:
It catch's the KeyError when there is no field `confirm_user` when it's only the user deleting it's own account.

2018-03-08 14:47 UTC, fnareoh commented on prologin/users/views.py
> +class DeleteView(PermissionRequiredMixin, UpdateView):
It's a remaining of [this code recommendation](https://simpleisbetterthancomplex.com/tutorial/2016/08/15/how-to-create-a-password-confirmation-view.html). It already had me worried but i couldn't change it, else it failed. I'll see if it's better now.

2018-03-08 14:47 UTC, fnareoh commented on prologin/users/templates/users/confirm_password.html
> +{% extends 'prologin/base.html' %}
yes

2018-03-08 14:59 UTC, fnareoh commented on prologin/users/views.py
> +            return render(self.request, 'users/delete.html', context)
I agree, but I didn't found out how.

2018-03-08 15:04 UTC, seirl commented on prologin/contest/models.py
> +    def qualification_finished(self):
He probably was talking about this line only:

    self.request.current_edition.is_active and self.request.current_events['qualification'].is_finished

2018-03-08 15:07 UTC, fnareoh commented on prologin/users/views.py
> +class DeleteView(PermissionRequiredMixin, UpdateView):
Getting it to FormView causes (I don't know why) problems of permissions, a regular user can't access the delete page of it's own count it reloads indefinitely a login page

2018-03-08 15:15 UTC, seirl commented on prologin/users/templates/users/edit.html
> +	<div class="Subhead Subhead--spacious">
lowercase class names

2018-03-08 19:10 UTC, zopieux requested changes

2018-03-08 19:10 UTC, zopieux commented on prologin/users/views.py
> +                "You can't delete your account during the contest. "
`_()` (translation, add final dot)

2018-03-08 19:10 UTC, zopieux commented on prologin/users/views.py
> +                             delete_username + "'s account has been succesfully deleted")
`_("%(user)s's account has been successfully deleted.") % {'user': deleted_username}` (translation, typo, final dot)

2018-03-08 19:10 UTC, zopieux commented on prologin/users/templates/users/edit.html
> +  <p>{% trans "Are you sure you sure you want to delete your account ?" %}</p>
**you sure you sure*, no space before *?*

2018-03-08 19:10 UTC, zopieux commented on prologin/users/templates/users/edit.html
> +  <p>{% trans "This will delete all your personnal information, all your posts on the forum and all the code you have submited." %}</p>
*personal*, *submitted*

2018-03-08 19:10 UTC, zopieux commented on prologin/users/templates/users/edit.html
> +  {% trans "Delete Account" %}</a>
No capital *A*

2018-03-08 19:10 UTC, zopieux commented on prologin/users/views.py
> +            form.add_error('confirm_password', 'Password does not match.')
Translation. Also there is just one password so just use eg. *Wrong password.* instead.

2018-03-08 19:10 UTC, zopieux commented on prologin/users/views.py
> +        context['form'] = users.forms.ConfirmDeleteForm(self.request.user)
Nah. You're doing the work of the `FormView` here.

2018-03-08 19:10 UTC, zopieux commented on prologin/users/views.py
> +                form.add_error('confirm_user', 'Username does not match.')
cf. password comment

2018-03-09 07:42 UTC, fnareoh commented on prologin/users/views.py
> +            form.add_error('confirm_password', 'Password does not match.')
I've look at the other error on form, what signifies the translation ?

2018-03-17 20:09 UTC, zopieux commented
Reworked and merged in 96c97a5c8f91f23766def270a329dd158abeb289. Thanks!

2018-03-17 20:09 UTC, closed without merging